version: "2.3"

volumes:
  root:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/yinglin8/tmpfile/docker-compose/var/kairosfs
      o: bind
  # edl-db-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/db
  #     o: bind
  # edl-resources-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/resources
  #     o: bind

services:
  main:
    image: fishinnorthernmostsea/kairos_main_api:api
    container_name: main
    command: python ./main.py ${KAIROS_LIB} --experiment ${EXPERIMENT} --performer ${PERFORMER_NAME} --port 10100 --oneie_addr oneie:20200 --edl_addr edl:20201 --coref_addr coref:20202 --temporal_addr temporal:20203 --mt_addr mt:20204 --ext_addr ext:20205 --matching_addr matching:20206 --relation_enrichment_addr relation-enrichment:20207 --gen_arg_addr gen-arg:20208 --visual_addr visual:20209 --fine_ent_addr fine-ent:20210 --upenn_temporal_addr upenn-temporal:30301 --input_mt_addr input-mt:20211 --weak_ed_addr weak-ed:20212 --weak_arg_addr weak-arg:20213 # -> --oneie_addr oneie.resin-resin-enclave.svc.cluster.local:20200 --edl_addr edl.resin-resin-enclave.svc.cluster.local:20201 --coref_addr coref.resin-resin-enclave.svc.cluster.local:20202 --temporal_addr temporal.resin-resin-enclave.svc.cluster.local:20203 --mt_addr mt.resin-resin-enclave.svc.cluster.local:20204 --ext_addr ext.resin-resin-enclave.svc.cluster.local:20205 --matching_addr matching.resin-resin-enclave.svc.cluster.local:20206 --relation_enrichment_addr relation-enrichment.resin-resin-enclave.svc.cluster.local:20207 --gen_arg_addr gen-arg.resin-resin-enclave.svc.cluster.local:20208 --visual_addr visual.resin-resin-enclave.svc.cluster.local:20209 --upenn_temporal_addr upenn-temporal.resin-resin-enclave.svc.cluster.local:30301
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 10100:10100 # For local docker-compose test

  input-mt:
    image: fishinnorthernmostsea/kairos_input_mt:api
    container_name: input-mt
    command: bash -c "python main.py -p 20211 -k 998e06f93b9c7bb9d7ff8ed4f1f0ff7aa6186b27946acd616847355278936375"
    ports:
      - 20211:20211 # For local docker-compose test

  fine-ent:
    image: wzq016/entity:api
    container_name: fine-ent
    command: bash -c "
      python ./process.py --port 20210"
    ports:
      - 20210:20210 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  weak-ed:
    image: fishinnorthernmostsea/kairos_weak_ed:api
    container_name: weak-ed
    command: bash -c "python main.py -p 20212"
    ports:
      - 20212:20212 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  weak-arg:
    image: zixuan11/amr_arg:api
    container_name: weak-arg
    command: bash -c "python server.py --port 20213"
    ports:
      - 20213:20213 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  oneie:
    image: limteng/oneie_kairos:api
    container_name: oneie
    command: bash -c "
      python /oneie/app.py --tmp_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/oneie --port 20200"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20200:20200 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  # edl-db:
  #   image: mongo:4
  #   container_name: edl-db
  #   logging:
  #       driver: none
  #   volumes:
  #     - edl-db-data:/data/db
  #   ports:
  #     - 27017:27017 # For local docker-compose test

  # edl:
  #   image: panx27/edl:api
  #   container_name: edl
  #   command: bash -c "
  #     python ./projs/docker_kairos/app.py --tmp_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/edl --port 20201"
  #   volumes:
  #     - edl-db-data:/data/db
  #     - edl-resources-data:/data/resources
  #     - root:${KAIROS_LIB}
  #   ports:
  #     - 20201:20201 # For local docker-compose test

  relation-enrichment:
    image: laituan245/relation_enrichment:api
    container_name: relation-enrichment
    command: bash -c "
      /opt/conda/envs/aida_coreference/bin/python3.6 main.py --tmp_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/relation_enrichment --port 20207"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20207:20207 # For local docker-compose test

  coref:
    image: laituan245/kairos_coref:api
    container_name: coref
    command: bash -c "
      /opt/conda/envs/aida_coreference/bin/python3.6 main.py --tmp_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/coref --port 20202"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20202:20202 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  temporal:
    image: wenhycs/uiuc_kairos_temporal_relation:api
    container_name: temporal
    working_dir: /roberta_temporal_relation
    command: bash -c "
      python api_run.py 20203 ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/temporal"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20203:20203 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  mt:
    image: panx27/kairos_mt:api
    container_name: mt
    command: bash -c "
      python web.py 20204"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20204:20204 # For local docker-compose test

  ext:
    image: panx27/kairos_extension:api
    container_name: ext
    command: bash -c "
      python ./app.py --tmp_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/ext --port 20205"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20205:20205 # For local docker-compose test

  matching:
    image: limteng/schema_matching:api
    container_name: matching
    command: bash -c "
      python /schema_matching/app.py --schema_dir ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/schemas --port 20206"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20206:20206 # For local docker-compose test

  upenn-temporal:
    image: slash0bz/temporal_kairos:latest
    container_name: upenn-temporal
    command: bash -c "
      python server.py 1 30301"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 30301:30301 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  gen-arg:
    image: raspberryice/gen-arg:api
    container_name: gen-arg
    command: bash -c "
      conda run -n genie python app.py --port=20208"
    volumes:
      - root:${KAIROS_LIB}
    ports:
      - 20208:20208 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu

  visual:
    image: xudonglin/cu_m2e2m:latest
    container_name: visual
    command: bash -c "
      source activate kairos-env;
      python graph_merging.py 20209 ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/input/task1/data/source/jpg/jpg/ ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/persist/visual/  ${KAIROS_LIB}/${EXPERIMENT}/${PERFORMER_NAME}/input/task1/docs/parent_children.tab;"
    volumes:
      - root:${KAIROS_LIB}
    shm_size: 16gb
    ports:
      - 20209:20209 # For local docker-compose test
    runtime: nvidia # For local docker-compose test
    environment:
     - NVIDIA_VISIBLE_DEVICES=0 # For local docker-compose test
    labels:
      - gpu
