version: "3"

volumes:
  root:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/yinglin8/tmpfile/docker-compose/var/kairosfs
      o: bind
  edl_db:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/db
      o: bind
  edl_data_dir:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data
      o: bind

services:
  main:
    image: panx27/kairos_preprocessing:0.1
    container_name: preprocessing
    command: ["python", "./create_path_structure.py", "/var/kairosfs"]
    volumes:
      - root:/var/kairosfs

  oneie:
    image: limteng/oneie_kairos:0.1
    container_name: oneie
    command: bash -c "
      python /oneie/predict.py -i /var/kairosfs/resin/resin/output/en/ltf -o /var/kairosfs/resin/resin/output/en/oneie -l en --output_hidden
      && python /oneie/predict.py -i /var/kairosfs/resin/resin/output/es/ltf -o /var/kairosfs/resin/resin/output/es/oneie -l es --output_hidden"
    volumes:
      - root:/var/kairosfs

  edl_db:
    image: mongo:4
    container_name: edl_db
    logging:
        driver: none
    volumes:
      - edl_db:/data/db

  edl:
    image: panx27/edl:0.1
    container_name: edl
    links:
      - "edl_db:mongo"
    command: ./wait-for-it.sh mongo:27017 --timeout=15 -- bash -c "
      python ./projs/docker_kairos/kairos.py en /var/kairosfs/resin/resin/output/en/oneie/m1_m2/mention/en.nam.tab /var/kairosfs/resin/resin/output/en/oneie/m1_m2/mention/en.nom.tab /var/kairosfs/resin/resin/output/en/oneie/m1_m2/mention/en.pro.tab /var/kairosfs/resin/resin/output/en/linking m36
      && python ./projs/docker_kairos/kairos.py es /var/kairosfs/resin/resin/output/es/oneie/m1_m2/mention/es.nam.tab /var/kairosfs/resin/resin/output/es/oneie/m1_m2/mention/es.nom.tab /var/kairosfs/resin/resin/output/es/oneie/m1_m2/mention/es.pro.tab /var/kairosfs/resin/resin/output/es/linking m36"
    volumes:
      - edl_data_dir:/data
      - root:/var/kairosfs
