version: "3"

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/yinglin8/tmpfile/docker-compose/
      o: bind
  edl_db:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/db
      o: bind
  edl_data_dir:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data
      o: bind

services:
  edl_db:
    image: mongo
    container_name: edl_db
    logging:
        driver: none
    volumes:
      - edl_db:/data/db

  kairos_data:
    image: panx27/kairos_entrypoint:0.1
    container_name: kairos_data
    command: ["python", "./download.py", "/data/resin"]
    volumes:
      - data_dir:/data/resin

  oneie:
    image: limteng/oneie_kairos:0.1
    container_name: oneie
    command: bash -c "
      python /oneie/predict.py -i /data/resin/input/en/ltf -o /data/resin/output/en/oneie -l en --output_hidden
      && python /oneie/predict.py -i /data/resin/input/es/ltf -o /data/resin/output/es/oneie -l es --output_hidden"
    volumes:
      - data_dir:/data/resin

  edl:
    image: panx27/edl:0.1
    container_name: edl
    links:
      - "edl_db:mongo"
    command: ./wait-for-it.sh mongo:27017 --timeout=15 -- bash -c "
      python ./projs/docker_kairos/kairos.py en /data/resin/output/en/oneie/m1_m2/mention/en.nam.tab /data/resin/output/en/oneie/m1_m2/mention/en.nom.tab /data/resin/output/en/oneie/m1_m2/mention/en.pro.tab /data/resin/output/en/linking m36
      && python ./projs/docker_kairos/kairos.py es /data/resin/output/es/oneie/m1_m2/mention/es.nam.tab /data/resin/output/es/oneie/m1_m2/mention/es.nom.tab /data/resin/output/es/oneie/m1_m2/mention/es.pro.tab /data/resin/output/es/linking m36"
    volumes:
      - edl_data_dir:/data
      - data_dir:/data/resin

  coref:
    image: laituan245/kairos_coref:0.1
    container_name: kairos_coref
    command: bash -c "
      /opt/conda/envs/aida_coreference/bin/python3.6 coref.py --ta 2 --language en --oneie_output /data/resin/output/en/oneie/m1_m2 --linking_output /data/resin/output/en/linking/en.linking.wikidata.cs --coreference_output /data/resin/output/en/coref
      && /opt/conda/envs/aida_coreference/bin/python3.6 coref.py --ta 2 --language es --oneie_output /data/resin/output/es/oneie/m1_m2 --linking_output /data/resin/output/es/linking/es.linking.wikidata.cs --coreference_output /data/resin/output/es/coref"
    volumes:
      - data_dir:/data/resin

  temporal_relation:
    image: wenhycs/uiuc_kairos_temporal_relation:0.1
    container_name: temporal_relation
    working_dir: /roberta_temporal_relation
    command: bash -c "
      python kairos_temporal_relation_pipeline.py --use_wait --wait_path /data/resin/output/en/coref --event_cold_start_filename /data/resin/output/en/coref/event.cs --ltf_path /data/resin/output/en/oneie/m1_m2/mention/en.nam.bio --output_filename /data/resin/output/en/temporal_relation.cs --use_tab
      && python post_processing.py --input_cs /data/resin/output/en/temporal_relation.cs --filtered_output_cs /data/resin/output/en/filtered_temporal_relation.cs
      && python sdf_converter.py --event_cs /data/resin/output/en/coref/event.cs --entity_cs /data/resin/output/en/coref/entity.cs --relation_cs /data/resin/output/en/coref/relation.cs --temporal_cs /data/resin/output/en/filtered_temporal_relation.cs --output_file /data/resin/output/en/graph_g.json"
    volumes:
      - data_dir:/data/resin
