version: "3"

volumes:
  root:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/yinglin8/tmpfile/docker-compose/var/kairosfs
      o: bind
  edl-db-data:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/db
      o: bind
  edl-resources-data:
    driver: local
    driver_opts:
      type: none
      device: /shared/nas/data/m1/xiaoman6/tmp/20201013_kairos_docker-compose/edl_data/resources
      o: bind

services:
  main:
    image: panx27/kairos_main_api:api
    container_name: main
    command: python ./main.py /var/kairosfs --port 10100 --oneie_addr oneie:20200 --edl_addr edl:20201 --coref_addr coref:20202 --temporal_addr temporal:20203 --mt_addr mt:20204 --ext_addr ext:20205 --matching_addr matching:20206 # -> --oneie_addr oneie.resin-resin-enclave.svc.cluster.local:20200 --edl_addr edl.resin-resin-enclave.svc.cluster.local:20201 --coref_addr coref.resin-resin-enclave.svc.cluster.local:20202 --temporal_addr temporal.resin-resin-enclave.svc.cluster.local:20203 --mt_addr mt.resin-resin-enclave.svc.cluster.local:20204 --ext_addr ext.resin-resin-enclave.svc.cluster.local:20205 --matching_addr matching.resin-resin-enclave.svc.cluster.local:20206
    volumes:
      - root:/var/kairosfs
    ports:
      - 10100:10100 # For local docker-compose test

  oneie:
    image: limteng/oneie_kairos:api
    container_name: oneie
    command: bash -c "
      python /oneie/app.py --tmp_dir /var/kairosfs/resin/resin/persist/oneie --port 20200"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20200:20200 # For local docker-compose test

  edl-db:
    image: mongo:4
    container_name: edl-db
    logging:
        driver: none
    volumes:
      - edl-db-data:/data/db
    ports:
      - 27017:27017 # For local docker-compose test

  edl:
    image: panx27/edl:api
    container_name: edl
    command: bash -c "
      python ./projs/docker_kairos/app.py --tmp_dir /var/kairosfs/resin/resin/persist/edl --port 20201"
    volumes:
      - edl-db-data:/data/db
      - edl-resources-data:/data/resources
      - root:/var/kairosfs
    ports:
      - 20201:20201 # For local docker-compose test

  coref:
    image: laituan245/kairos_coref:api
    container_name: coref
    command: bash -c "
      /opt/conda/envs/aida_coreference/bin/python3.6 main.py --tmp /var/kairosfs/resin/resin/persist/coref --port 20202"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20202:20202 # For local docker-compose test

  temporal:
    image: wenhycs/uiuc_kairos_temporal_relation:api
    container_name: temporal
    working_dir: /roberta_temporal_relation
    command: bash -c "
      python api_run.py 20203 /var/kairosfs/resin/resin/persist/temporal"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20203:20203 # For local docker-compose test

  mt:
    image: yrf1/kairos_mt:api
    container_name: mt
    command: bash -c "
      python web.py 20204"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20204:20204 # For local docker-compose test

  ext:
    image: panx27/kairos_extension:api
    container_name: ext
    command: bash -c "
      python ./app.py --tmp_dir /var/kairosfs/resin/resin/persist/ext --port 20205"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20205:20205 # For local docker-compose test

  ext:
    image: panx27/kairos_extension:api
    container_name: ext
    command: bash -c "
      python ./app.py --tmp_dir /var/kairosfs/resin/resin/persist/ext --port 20205"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20205:20205 # For local docker-compose test

  matching:
    image: limteng/schema_matching:api
    container_name: matching
    command: bash -c "
      python /schema_matching/app.py --port 20206"
    volumes:
      - root:/var/kairosfs
    ports:
      - 20206:20206 # For local docker-compose test
    environment: # For local docker-compose test
      - KAIROS_LIB=/var/kairosfs
      - EXPERIMENT=resin
      - PERFORMER_NAME=resin

  # visual:
  #   image: xudonglin/cu_m2e2m
  #   container_name: cu_m2e2m
  #   command: bash -c "
  #     python create_list.py ./ q4_frames.txt"
  #   volumes:
  #     - root:/var/kairosfs
  #   ports:
  #     - 20209:20209 # For local docker-compose test    
